### ISSUE TITLE
Processor部分代码的问题

### ISSUE THREAD

**Issue by wjjwsl** [supercoderhawk/DeepLearning_NLP#4]
`def read_dictionary(self, dict_path: str, reverse=False):

    dictionary = {}
    with open(dict_path, encoding='utf8') as d:
      items = d.readlines()
      for item in items:
        pair = item.split(' ')
        dictionary[pair[0]] = int(pair[1])
    if reverse:
      return dictionary, dict(zip(dictionary.values(), dictionary.keys()))
    else:
      return dictionary
`

这段代码我有点看不懂，dictionary明明是空的为什么会有dictionary[pair[0]]？还有pair[1]不是string么，怎么可以int(pair[1])呢？谢谢解答！

**Comment by supercoderhawk** [comment]
1.Python中dict赋值。
2.pair[1]为数字的字符串形式，int(pair[1])是强制类型转换。
